// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWYjqr-HFExex4W9N02YkOs5Q-h0fR8x0',
    appId: '1:399417625561:web:f78e1b25d42fe29108e7c8',
    messagingSenderId: '399417625561',
    projectId: 'complaintapp-21969',
    authDomain: 'complaintapp-21969.firebaseapp.com',
    storageBucket: 'complaintapp-21969.firebasestorage.app',
    measurementId: 'G-JY6BNJ2JN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpiZMMdAUKwhLQREWlKAwCVsi7ikF6rCU',
    appId: '1:399417625561:android:267b0d588b28237508e7c8',
    messagingSenderId: '399417625561',
    projectId: 'complaintapp-21969',
    storageBucket: 'complaintapp-21969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1p3h7MptfOgh-EbXRqOgp3cIZNsY9Zbw',
    appId: '1:399417625561:ios:bd386e0115540a6b08e7c8',
    messagingSenderId: '399417625561',
    projectId: 'complaintapp-21969',
    storageBucket: 'complaintapp-21969.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1p3h7MptfOgh-EbXRqOgp3cIZNsY9Zbw',
    appId: '1:399417625561:ios:bd386e0115540a6b08e7c8',
    messagingSenderId: '399417625561',
    projectId: 'complaintapp-21969',
    storageBucket: 'complaintapp-21969.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWYjqr-HFExex4W9N02YkOs5Q-h0fR8x0',
    appId: '1:399417625561:web:f78e1b25d42fe29108e7c8',
    messagingSenderId: '399417625561',
    projectId: 'complaintapp-21969',
    authDomain: 'complaintapp-21969.firebaseapp.com',
    storageBucket: 'complaintapp-21969.firebasestorage.app',
    measurementId: 'G-JY6BNJ2JN9',
  );

}